// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENUINHeoRDJzbbfy29no8jwwiiJt3Dss',
    appId: '1:744459624156:web:ed6bdf2f1d1c10f95ede19',
    messagingSenderId: '744459624156',
    projectId: 'firebase-coentrepreneurs-bts',
    authDomain: 'fir-coentrepreneurs-bts.firebaseapp.com',
    storageBucket: 'firebase-coentrepreneurs-bts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_nTym6SRhPzk8_OQv0ohJ-A0jf4fPTw',
    appId: '1:744459624156:android:8b754bc3cf0720205ede19',
    messagingSenderId: '744459624156',
    projectId: 'firebase-coentrepreneurs-bts',
    storageBucket: 'firebase-coentrepreneurs-bts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWW8uA7DuGOwbVOdMWMvHkVCBZXcFeh5Y',
    appId: '1:744459624156:ios:7843ded56a34512e5ede19',
    messagingSenderId: '744459624156',
    projectId: 'firebase-coentrepreneurs-bts',
    storageBucket: 'firebase-coentrepreneurs-bts.firebasestorage.app',
    iosBundleId: 'com.example.coentrepreneurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWW8uA7DuGOwbVOdMWMvHkVCBZXcFeh5Y',
    appId: '1:744459624156:ios:7843ded56a34512e5ede19',
    messagingSenderId: '744459624156',
    projectId: 'firebase-coentrepreneurs-bts',
    storageBucket: 'firebase-coentrepreneurs-bts.firebasestorage.app',
    iosBundleId: 'com.example.coentrepreneurs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENUINHeoRDJzbbfy29no8jwwiiJt3Dss',
    appId: '1:744459624156:web:c4b4d64a0a06fbbc5ede19',
    messagingSenderId: '744459624156',
    projectId: 'firebase-coentrepreneurs-bts',
    authDomain: 'fir-coentrepreneurs-bts.firebaseapp.com',
    storageBucket: 'firebase-coentrepreneurs-bts.firebasestorage.app',
  );
}
