// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0WWXmG54WRWb10XppdvJsxtZtuojjsdc',
    appId: '1:324815572845:web:760a3ad54952ab2913d464',
    messagingSenderId: '324815572845',
    projectId: 'coentrepreneurs-7b291',
    authDomain: 'coentrepreneurs-7b291.firebaseapp.com',
    storageBucket: 'coentrepreneurs-7b291.firebasestorage.app',
    measurementId: 'G-XDQTK3BH70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEK67NEsEwBgYi9CnlKfWTb_LTxIxK5CI',
    appId: '1:324815572845:android:1cf6f5a1303e6dd213d464',
    messagingSenderId: '324815572845',
    projectId: 'coentrepreneurs-7b291',
    storageBucket: 'coentrepreneurs-7b291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZkXSV5jmc8ZlF7w0gv50qx5rLmvN5ewg',
    appId: '1:324815572845:ios:6d596f8d8849533613d464',
    messagingSenderId: '324815572845',
    projectId: 'coentrepreneurs-7b291',
    storageBucket: 'coentrepreneurs-7b291.firebasestorage.app',
    iosBundleId: 'com.example.coentrepreneurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZkXSV5jmc8ZlF7w0gv50qx5rLmvN5ewg',
    appId: '1:324815572845:ios:6d596f8d8849533613d464',
    messagingSenderId: '324815572845',
    projectId: 'coentrepreneurs-7b291',
    storageBucket: 'coentrepreneurs-7b291.firebasestorage.app',
    iosBundleId: 'com.example.coentrepreneurs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0WWXmG54WRWb10XppdvJsxtZtuojjsdc',
    appId: '1:324815572845:web:2f79064c850cd84f13d464',
    messagingSenderId: '324815572845',
    projectId: 'coentrepreneurs-7b291',
    authDomain: 'coentrepreneurs-7b291.firebaseapp.com',
    storageBucket: 'coentrepreneurs-7b291.firebasestorage.app',
    measurementId: 'G-KZCNEQ4QNE',
  );

}